server:
  port: 8080

spring:
  application:
    name: athly-gateway
  cloud:
    gateway:
      routes:
        - id: athly-user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: athly-workout
          uri: http://localhost:8082
          predicates:
            - Path=/api/workouts/**
          filters:
            - StripPrefix=2
        - id: athly-nutrition
          uri: http://localhost:8083
          predicates:
            - Path=/api/nutrition/**
          filters:
            - StripPrefix=2
