server:
  port: 8080

spring:
  application:
    name: athly-gateway
  cloud:
    gateway:
      routes:
        - id: athly-user
          uri: http://localhost:8081
          predicates:
            - Path=/user-management/**
          filters:
            - StripPrefix=1
        - id: athly-workout
          uri: http://localhost:8082
          predicates:
            - Path=/workout-management/**
          filters:
            - StripPrefix=1
        - id: athly-nutrition
          uri: http://localhost:8083
          predicates:
            - Path=/nutrition-management/**
          filters:
            - StripPrefix=1
